version: "2.0"

services:

  postgres_buildly:
    container_name: postgres_buildly
    image: postgres:9.6
    environment:
      POSTGRES_DB: buildly
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data/
    restart: always

  buildly:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/scripts/run-standalone-dev.sh
    container_name: buildly
    image: buildly
    volumes:
      - .:/code
      - static-content:/static
    ports:
      - "8080:8080"
    depends_on:
      - postgres_buildly
    environment:
      DJANGO_SETTINGS_MODULE: "buildly.settings.production"
      ALLOWED_HOSTS: "*"
      CORS_ORIGIN_ALLOW_ALL: "True"
      CORS_ORIGIN_WHITELIST: "*"
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "buildly"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres_buildly"
      DATABASE_PORT: "5432"
      DEFAULT_ORG: "Uprising"
      AUTO_APPROVE_USER: "True"
      JWT_ISSUER: "buildly"
      JWT_PRIVATE_KEY_RSA_BUILDLY: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIBOwIBAAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRBqhqvJu1hKPYn9HYd75c0
        gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQJAe5z5096oyeqGX6J+RGGx
        11yuDJ7J+0N4tthUHSWWUtgkd19NvmTM/mVLmPCzZHgNUT+aWUKsQ84+jhru/NQD
        0QIhAOHOzFmjxjTAR1jspn6YtJBKQB40tvT6WEvm2mKm0aD7AiEAyRPwXyZf3JT+
        M6Ui0Mubs7Qb/E4g1d/kVL+o/XoZC6cCIQC+nKzPtnooKW+Q1yOslgdGDgeV9/XB
        Ulqap+MNh7hJZQIgZNaM+wqhlFtbx8aO2SrioJI4XqVHrjojpaSgOM3cdY0CIQDB
        Q6ckOaDV937acmWuiZhxuG2euNLwNbMldtCV5ADo/g==
        -----END RSA PRIVATE KEY-----
      JWT_PUBLIC_KEY_RSA_BUILDLY: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB
        qhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==
        -----END PUBLIC KEY-----
      SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URL: "https://localhost:8000/complete/google-oauth2"
      SOCIAL_AUTH_LOGIN_REDIRECT_URL: "http://localhost:8080/"
      SOCIAL_AUTH_MICROSOFT_GRAPH_REDIRECT_URL: "https://localhost:8000/complete/microsoft-graph"
      ACCESS_TOKEN_EXPIRE_SECONDS: "86400"
      SECRET_KEY: "ek*)b=mtcc7q1cym@oox(lyrz1ncz-(w+(#&u7l-&)7a8wv#_k"
      OAUTH_CLIENT_ID: "wkXLlC9h3k0jxIx7oLllxpFVU89Dxgi7O8FYZyfX"
      OAUTH_CLIENT_SECRET: "KiKRft8MajLabQId7pjSsa3OfvJAXN9NENi0tVRTX3Vbthr6iClEDZZtbyGuD9M8UbKpK2E8R4xJYUolZxg1nVa1iZwhQPi5ionOKdpIs4de2bmUaZ0qWi4MdBmdwDvF"
      USE_PASSWORD_USER_ATTRIBUTE_SIMILARITY_VALIDATOR: "True"
      USE_PASSWORD_MINIMUM_LENGTH_VALIDATOR: "True"
      PASSWORD_MINIMUM_LENGTH: "6"
      USE_PASSWORD_COMMON_VALIDATOR: "True"
      USE_PASSWORD_NUMERIC_VALIDATOR: "True"
      FRONTEND_URL: "http://localhost:3000/"
      EMAIL_HOST: "smtp.sendgrid.net"
      EMAIL_HOST_USER: "apikey"
      EMAIL_HOST_PASSWORD: "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"
      EMAIL_PORT: "587"
      EMAIL_USE_TLS: "False"
      EMAIL_SUBJECT_PREFIX: "NO REPLY: Buildly - "
      EMAIL_BACKEND: "SMTP"
      DEFAULT_FROM_EMAIL: "admin@buildly.io"
      RESETPASS_CONFIRM_URL_PATH: "reset-password-confirm/"
      SELF_SSL_BUNDLE: "/code/self-ssl-bundle.crt"
      GCP_PROJECT: 'uprising-web'
      GCP_CLIENT_ID: '114637864365214335773'
      GCP_CLOUD_STORAGE: 'uprising-dev-bucket'
      GCP_CLIENT_EMAIL: 'universal@uprising-web.iam.gserviceaccount.com'
      GCP_PRIVATE_KEY_ID: '6dbde3b169294b9b16af1f85de7894c237b57c10'
      GCP_PRIVATE_KEY: |-
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCzs3asO8/ZLKLW
        4SFF05pSI3/P2h9H/+OFsIuuYMJ+EFckgF2mLCgWAFUISAOMJ/eUS8p986z3/HUJ
        3V16UR+RDwGjgM4vhosaWCwFcpTLFrv/0TvxSREnfQ5Z/KZyX9pAEF+9gUyK11tr
        RuzlBmQX9E4gSgtDEYC0h2ncDNGCb0zvRqd5+SS5NLg8PFMTsGsbF6/KiVWrc6ha
        TrOZvUmLDJE0E9jg/YRhLpcWOAXVKo7vcpOoWftXyTMDNcczOcD/PYrcgsqbydhQ
        wEhMNzz8tXuUfRL4QwN0q3YiDkDahXHdptbUgO/0CKkRzwvluigtsrP9KHlRbNBx
        pwzmd/V3AgMBAAECggEANwjEVHUw75sK9/IUxZTLk1JJ53cu01cb8CqkbLA3gHIy
        rfweMjEdybcqU5HyfC8VVLZtemtxUrVfhrjj0v0bRMqqvs9I1idHXLcaLETuKtB4
        nR0QVZICDezvw0FsHGUcqzgYiioaLf9MgStEi9OMPgXVE3B5yH2IxEEge4L1exNl
        n5MiRfFnYd2/C5Za5kJxf+gtuAK0IobpiGhbu9ssIGcg9N5/LZYJGLu4oU48lO+n
        uUkVekgIxKPBX09bmuNZt7dtd+0yyCLrgQREy1lceRdTXEsEElYYLcPEU2KuQAGE
        Ao49aY3Mvg9HJ3CPIqx4DqKSN/vhqpOe2bMs3eIw8QKBgQDg5EqgDTyfai15uZ8N
        LQ92GyLeLdPrxRa4CR3JyED5AD3deJfgJgFvkU91+J3SqErUvxBYNNL9wxtRkIc3
        Ts0G1qYh9ztqGuH+blSF/SGpMGvBgW4H5zxVeFVklxB7ZiA4HKUpk4bG134Vsgqx
        YTX0Pkm1kezBfEY9hkj6Vy/heQKBgQDMjujfk/lbSoy8eLlt5FDVvw05LZWJqz6L
        IT9ZkorRJAbRefUdhtc2IVngS7mhBEkPZCubViwTA0tTJImCvTEXVLiOkYxe9/zP
        y9kVBzWelS1rGiIBPapd/WiGARzYsVpsEgV3IBsGlhSuWprhcmWiG/EM4CrSkswF
        z1HLlDRCbwKBgQCJ2QUxA8wT/vYu9atbXTJr94gw3bBXhTA+0D+1Do1c01wYY7Hc
        UA9zPoORUToUBNoRe6feGUr3Bt+46DkpmqCrv2iHy05c5GuAFEq08orudOKn8tjp
        +UAPN7pH9RzCNsArBMvsJyRmv3HmhIJvZaG3u3Jc3DxeAPng/m2/HTAZKQKBgFaj
        DHRtKsaEi5jjlL27XpU5BrO538TgF2w716XrUAoGNTERc0RfMNVHSNabm/Jba0ou
        hd2ToLUoxwVeyzLpSFp2UnhnoskyRQwJbVbfp9ETo5niBpb59Cc8xcFDxWDttLti
        4peyrF+cvwOdck2b8vm21eA7LUfkTq8DQMR1b7DXAoGAOWsdtkxVuJC/RXM2KbvU
        yQ3ZYMGwDE3Ui8v/eQCs3/Erm3++E52/R0p5mTgo/pqGJzaufNBIcFJp/kb7im4e
        u1OWFur3HtvyEe85l+nstmoGWvMRemhKtuIPQjfNDf/zO3m4xByzRZEw3j8fdVWc
        3Yz9eK2ZQaZWAxPj0icZ46Y=
        -----END PRIVATE KEY-----

volumes:
  static-content:
