# Generated by Django 2.2.27 on 2022-06-07 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200303_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriber_uuid', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Subscriber UUID')),
                ('email', models.EmailField(max_length=254, verbose_name='Subscriber Email')),
            ],
            options={
                'verbose_name': 'Uprising Subscriber',
                'verbose_name_plural': 'Uprising Subscribers',
                'ordering': ('email',),
            },
        ),
    ]
