# Generated by Django 2.2.27 on 2022-07-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='User avatar'),
        ),
    ]
