# Generated by Django 2.2.27 on 2022-07-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coreuser_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='about_me',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
